version: '3.3'

services:
  url-shortener_db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: url-shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15433:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:4.9.1-arm64
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - SERVICES=s3,dynamodb
    ports:
      - "4566:4566"
    volumes:
      - ./docker/aws:/etc/localstack/init/ready.d
    healthcheck:
      test: curl -s localhost:4566 | grep running > /dev/null || exit 1
      interval: 5s
      timeout: 3s