version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    resource_class: medium
    docker:
      - image: cimg/node:20.10.0
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_DB: url-shortener
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_SCHEMA: test
          # TZ: 'GMT+7'
          # PGTZ: 'GMT+7'
    parallelism: 5
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/url-shortener?schema=test&connection_limit=2
      JWT_PRIVATE_KEY: src/certs/jwt/private.pem
      JWT_PUBLIC_KEY: src/certs/jwt/public.pem
      MEMBER_EXPIRES_IN: 30d
      GUESS_EXPIRES_IN: 24h
      TOKEN_EXPIRES_IN: 30d
    steps:
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - run:
          name: Check Node Version
          command: node --version
      - run:
          name: Check test folder file
          working_directory: ./test
          command: ls -a
      - node/install-packages:
          app-dir: ./
          cache-path: ./node_modules
          override-ci-command: yarn install
      - run:
          name: Run Migration
          command: yarn migration:up
          working_directory: ./
      - run:
          command: yarn test
          working_directory: ./
          name: Unit Testing
      - run:
          command: yarn test:e2e
          working_directory: ./
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
